"""empty message

Revision ID: 26db68807bbb
Revises: 
Create Date: 2025-03-08 15:20:19.525599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26db68807bbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
